# Site Settings
encoding: UTF-8
languages: ["pt", "en", "es"]
default_lang: "pt"
exclude_from_localization: ["javascripts", "images", "css", "README.md", "LICENSE", "fonts", "musicas", "documentos", "scripts"]
parallel_localization: true
permalink: /blog/:year/:month/:day/:title/

whitelist: [jekyll-redirect-from, jekyll-seo-tag, jekyll-sitemap]
plugins:
  - jekyll-redirect-from
  - jekyll-polyglot
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
kramdown:
  auto_id_prefix: 'heading-'
  smart_quotes: ["apos", "apos", "quot", "quot"]
  toc_levels: 1..3

sass:
  style: compressed

# Site Data
url: https://portalsemporteiras.github.io # the base hostname & protocol for your site, e.g. http://example.com
baseurl: # the subpath of your site, e.g. /blog
title: PSP
description: "Rede Comunnitária PSP."
keywords: 'communitynetwork, rede comunitária, redes mesh, internet'
author:
  name: "Portal Sem Porteiras"
  location: "Bairro dos Souzas - Monteiro Lobato/SP - Brasil"
  email: portalsemporteiras@gmail.com
  social_links:
    - name: instagram
      url: https://www.instagram.com/portalsemporteiras/
home:
  section2: <h2>Rede de Comunicação Comunitária</h2>
  section3: <h3>Bairro dos Souzas - Monteiro Lobato</h3>
blog:
  cc_license: http://creativecommons.org/licenses/by-sa/4.0/ # A link to CC License of your choice.
  cc_license_image: /assets/images/theme/cc-by-sa.png # An image of your CC License.
  footer_content: Uma rede feita de gente

disqus:
  shortname: # e.g. yizeng
  public_key: # e.g. ULZ0b9TFefCUJHKQd4JCKv2v3u27YoG7YG8zXPewkWrT333Z0Se9YnxLzoV6VM8W
google_tag_manager: # e.g. 'GTM-KCQJXZ8F'
addthis_public_id: # AddThis sharing plugin. See http://www.addthis.com/. E.g. ra-53329e27694534j5

paths:
  home: /
  blog: /blog/
  categories: /blog/categories/
  tags: /blog/tags/
